Managing of isolate instances
CascadeBot/Command-Processor pull request #1
Opened 2022-10-03 00:24 UTC by weeryan17

2022-10-03 07:17 UTC, mrjvs requested changes
im not 100% convinced classes is the way to go here completely,
on a single isolate instance I can see it being useful.
but anything else I'd just make use of standard js modules (which are like singleton imports)

2022-10-03 07:17 UTC, mrjvs commented on src/models/isolate-instance.ts
> +        const newContext = await createContext();
wrong createContext()

2022-10-03 11:14 UTC, weeryan17 commented
> im not 100% convinced classes is the way to go here completely, on a single isolate instance I can see it being useful. but anything else I'd just make use of standard js modules (which are like singleton imports)

Yegh probably don't need a class for the isolate manager thinking about it. I think it's still useful for the isolate instances, but maybe not the manager.

2022-10-03 14:55 UTC, mrjvs approved these changes

2022-10-06 17:29 UTC, mrjvs approved these changes

2022-10-06 17:31 UTC, merged